// Re-export everything from shared-types for convenient local imports.
// Components import from here rather than the package path directly.
export type {
  Character,
  Move,
  Relic,
  MoveType,
  StatKey,
  StatusEffectType,
  BattlePhase,
  PlayerKey,
  BattleState,
  BattleFighterState,
  PlayerBattleState,
  BattleAction,
  BattleLogEntry,
  ActiveStatusEffect,
  ActiveStatModifier,
  StatBlock,
  TeamDoc,
  TeamSlot,
  LobbyUser,
  ChatMessage,
  AuthResponse,
  LoginRequest,
  RegisterRequest,
  ClientToServerEvents,
  ServerToClientEvents,
  InterServerEvents,
  SocketData,
} from '@anime-showdown/shared-types';
